# 测试 Qwen API 接口

### GET 请求测试
GET http://localhost:8080/api/qwen
Accept: application/json

### POST 请求测试 (如果接口支持POST)
POST http://localhost:8080/api/qwen/chat
Content-Type: application/json
Accept: application/json

{
  "prompt": "他有哪些主要对手？"
}

### POST 请求测试 (如果接口支持POST)
POST http://localhost:8080/api/qwen/aiservicesimplechat
Content-Type: application/json
Accept: application/json

{
  "prompt": "你好，请介绍一下自己，包括详细的版本信息以及当前的年月日时分秒"
}

### 测试带参数的 GET 请求
GET http://localhost:8080/api/qwen?query=你好世界
Accept: application/json


### POST 请求测试 (如果接口支持POST)
POST http://localhost:8080/api/qwen/aiservicetemplatechat
Content-Type: application/json
Accept: application/json

{
  "prompt": "三国演义"
}

### POST 使用系统消息的模板对话
POST http://localhost:8080/api/qwen/aiservicetemplatechatwithsysmsg
Content-Type: application/json
Accept: application/json

{
  "prompt": "三国演义"
}

### POST 模拟多轮对话
POST http://localhost:8080/api/qwen/simulatemultiroundchat
Content-Type: application/json
Accept: application/json

{
  "prompt": "他有哪些主要对手？"
}

### POST 使用 ChatRequest 作为入参
POST http://localhost:8080/api/qwen/usechatrequest
Content-Type: application/json
Accept: application/json

{
  "prompt": "Java最新版本有哪些特性？"
}

### POST 使用 ChatRequest 作为入参
POST http://localhost:8080/api/qwen/useimage
Content-Type: application/json
Accept: application/json

{
  "imageUrl": "https://dashscope-result-wlcb-acdr-1.oss-cn-wulanchabu-acdr-1.aliyuncs.com/1d/38/20251204/df817e52/531abcea-2223-46e4-b498-e0bcb08ae4d669232545.png?Expires=1764920223&OSSAccessKeyId=LTAI5tKPD3TMqf2Lna1fASuh&Signature=NggZvRG5OcPlpTO6Nop1BwtzMLk%3D",
  "prompt": "图片中有什么？"
}

### POST 使用图像模型生成图片
POST http://localhost:8080/api/qwen/generateimage
Content-Type: application/json
Accept: application/json

{
  "prompt": "生成一张图片，内容是三国演义中的孔明借东风",
  "imageNum": 2
}

### POST 使用图像模型编辑图片
POST http://localhost:8080/api/qwen/editimage
Content-Type: application/json
Accept: application/json

{
  "prompt": "图1中的女生穿着图2中的黑色裙子按图3的姿势坐下",
  "imageUrls": [
    "https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20250925/thtclx/input1.png",
    "https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20250925/iclsnx/input2.png",
    "https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20250925/gborgw/input3.png"
  ]
}