// 协议类型

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: grpcstream.proto

// 包名

package grpcstream

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 服务端请求的数据结构
type SingleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SingleRequest) Reset() {
	*x = SingleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcstream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleRequest) ProtoMessage() {}

func (x *SingleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcstream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleRequest.ProtoReflect.Descriptor instead.
func (*SingleRequest) Descriptor() ([]byte, []int) {
	return file_grpcstream_proto_rawDescGZIP(), []int{0}
}

func (x *SingleRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 服务端响应的数据结构
type SingleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SingleResponse) Reset() {
	*x = SingleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcstream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleResponse) ProtoMessage() {}

func (x *SingleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcstream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleResponse.ProtoReflect.Descriptor instead.
func (*SingleResponse) Descriptor() ([]byte, []int) {
	return file_grpcstream_proto_rawDescGZIP(), []int{1}
}

func (x *SingleResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SingleResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_grpcstream_proto protoreflect.FileDescriptor

var file_grpcstream_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x72, 0x70, 0x63, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x67, 0x72, 0x70, 0x63, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0x1f,
	0x0a, 0x0d, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x34, 0x0a, 0x0e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xcf, 0x02, 0x0a, 0x11, 0x49, 0x47, 0x72, 0x70, 0x63, 0x53,
	0x74, 0x72, 0x65, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x13, 0x53,
	0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e,
	0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x12, 0x53, 0x69, 0x6e,
	0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x53, 0x69, 0x6e,
	0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x4d, 0x0a, 0x12, 0x4d, 0x75, 0x6c, 0x74,
	0x69, 0x52, 0x65, 0x71, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x19,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x53, 0x69, 0x6e, 0x67,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x4e, 0x0a, 0x11, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x52, 0x65, 0x71, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x65, 0x73, 0x70, 0x12, 0x19, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpcstream_proto_rawDescOnce sync.Once
	file_grpcstream_proto_rawDescData = file_grpcstream_proto_rawDesc
)

func file_grpcstream_proto_rawDescGZIP() []byte {
	file_grpcstream_proto_rawDescOnce.Do(func() {
		file_grpcstream_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcstream_proto_rawDescData)
	})
	return file_grpcstream_proto_rawDescData
}

var file_grpcstream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpcstream_proto_goTypes = []interface{}{
	(*SingleRequest)(nil),  // 0: grpcstream.SingleRequest
	(*SingleResponse)(nil), // 1: grpcstream.SingleResponse
}
var file_grpcstream_proto_depIdxs = []int32{
	0, // 0: grpcstream.IGrpcStremService.SingleReqSingleResp:input_type -> grpcstream.SingleRequest
	0, // 1: grpcstream.IGrpcStremService.SingleReqMultiResp:input_type -> grpcstream.SingleRequest
	0, // 2: grpcstream.IGrpcStremService.MultiReqSingleResp:input_type -> grpcstream.SingleRequest
	0, // 3: grpcstream.IGrpcStremService.MultiReqMultiResp:input_type -> grpcstream.SingleRequest
	1, // 4: grpcstream.IGrpcStremService.SingleReqSingleResp:output_type -> grpcstream.SingleResponse
	1, // 5: grpcstream.IGrpcStremService.SingleReqMultiResp:output_type -> grpcstream.SingleResponse
	1, // 6: grpcstream.IGrpcStremService.MultiReqSingleResp:output_type -> grpcstream.SingleResponse
	1, // 7: grpcstream.IGrpcStremService.MultiReqMultiResp:output_type -> grpcstream.SingleResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcstream_proto_init() }
func file_grpcstream_proto_init() {
	if File_grpcstream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpcstream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcstream_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcstream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcstream_proto_goTypes,
		DependencyIndexes: file_grpcstream_proto_depIdxs,
		MessageInfos:      file_grpcstream_proto_msgTypes,
	}.Build()
	File_grpcstream_proto = out.File
	file_grpcstream_proto_rawDesc = nil
	file_grpcstream_proto_goTypes = nil
	file_grpcstream_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IGrpcStremServiceClient is the client API for IGrpcStremService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IGrpcStremServiceClient interface {
	// 单项流式 ：单个请求，单个响应
	SingleReqSingleResp(ctx context.Context, in *SingleRequest, opts ...grpc.CallOption) (*SingleResponse, error)
	// 服务端流式 ：单个请求，集合响应
	SingleReqMultiResp(ctx context.Context, in *SingleRequest, opts ...grpc.CallOption) (IGrpcStremService_SingleReqMultiRespClient, error)
	// 客户端流式 ：集合请求，单个响应
	MultiReqSingleResp(ctx context.Context, opts ...grpc.CallOption) (IGrpcStremService_MultiReqSingleRespClient, error)
	// 双向流式 ：集合请求，集合响应
	MultiReqMultiResp(ctx context.Context, opts ...grpc.CallOption) (IGrpcStremService_MultiReqMultiRespClient, error)
}

type iGrpcStremServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIGrpcStremServiceClient(cc grpc.ClientConnInterface) IGrpcStremServiceClient {
	return &iGrpcStremServiceClient{cc}
}

func (c *iGrpcStremServiceClient) SingleReqSingleResp(ctx context.Context, in *SingleRequest, opts ...grpc.CallOption) (*SingleResponse, error) {
	out := new(SingleResponse)
	err := c.cc.Invoke(ctx, "/grpcstream.IGrpcStremService/SingleReqSingleResp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iGrpcStremServiceClient) SingleReqMultiResp(ctx context.Context, in *SingleRequest, opts ...grpc.CallOption) (IGrpcStremService_SingleReqMultiRespClient, error) {
	stream, err := c.cc.NewStream(ctx, &_IGrpcStremService_serviceDesc.Streams[0], "/grpcstream.IGrpcStremService/SingleReqMultiResp", opts...)
	if err != nil {
		return nil, err
	}
	x := &iGrpcStremServiceSingleReqMultiRespClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type IGrpcStremService_SingleReqMultiRespClient interface {
	Recv() (*SingleResponse, error)
	grpc.ClientStream
}

type iGrpcStremServiceSingleReqMultiRespClient struct {
	grpc.ClientStream
}

func (x *iGrpcStremServiceSingleReqMultiRespClient) Recv() (*SingleResponse, error) {
	m := new(SingleResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *iGrpcStremServiceClient) MultiReqSingleResp(ctx context.Context, opts ...grpc.CallOption) (IGrpcStremService_MultiReqSingleRespClient, error) {
	stream, err := c.cc.NewStream(ctx, &_IGrpcStremService_serviceDesc.Streams[1], "/grpcstream.IGrpcStremService/MultiReqSingleResp", opts...)
	if err != nil {
		return nil, err
	}
	x := &iGrpcStremServiceMultiReqSingleRespClient{stream}
	return x, nil
}

type IGrpcStremService_MultiReqSingleRespClient interface {
	Send(*SingleRequest) error
	CloseAndRecv() (*SingleResponse, error)
	grpc.ClientStream
}

type iGrpcStremServiceMultiReqSingleRespClient struct {
	grpc.ClientStream
}

func (x *iGrpcStremServiceMultiReqSingleRespClient) Send(m *SingleRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *iGrpcStremServiceMultiReqSingleRespClient) CloseAndRecv() (*SingleResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SingleResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *iGrpcStremServiceClient) MultiReqMultiResp(ctx context.Context, opts ...grpc.CallOption) (IGrpcStremService_MultiReqMultiRespClient, error) {
	stream, err := c.cc.NewStream(ctx, &_IGrpcStremService_serviceDesc.Streams[2], "/grpcstream.IGrpcStremService/MultiReqMultiResp", opts...)
	if err != nil {
		return nil, err
	}
	x := &iGrpcStremServiceMultiReqMultiRespClient{stream}
	return x, nil
}

type IGrpcStremService_MultiReqMultiRespClient interface {
	Send(*SingleRequest) error
	Recv() (*SingleResponse, error)
	grpc.ClientStream
}

type iGrpcStremServiceMultiReqMultiRespClient struct {
	grpc.ClientStream
}

func (x *iGrpcStremServiceMultiReqMultiRespClient) Send(m *SingleRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *iGrpcStremServiceMultiReqMultiRespClient) Recv() (*SingleResponse, error) {
	m := new(SingleResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// IGrpcStremServiceServer is the server API for IGrpcStremService service.
type IGrpcStremServiceServer interface {
	// 单项流式 ：单个请求，单个响应
	SingleReqSingleResp(context.Context, *SingleRequest) (*SingleResponse, error)
	// 服务端流式 ：单个请求，集合响应
	SingleReqMultiResp(*SingleRequest, IGrpcStremService_SingleReqMultiRespServer) error
	// 客户端流式 ：集合请求，单个响应
	MultiReqSingleResp(IGrpcStremService_MultiReqSingleRespServer) error
	// 双向流式 ：集合请求，集合响应
	MultiReqMultiResp(IGrpcStremService_MultiReqMultiRespServer) error
}

// UnimplementedIGrpcStremServiceServer can be embedded to have forward compatible implementations.
type UnimplementedIGrpcStremServiceServer struct {
}

func (*UnimplementedIGrpcStremServiceServer) SingleReqSingleResp(context.Context, *SingleRequest) (*SingleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SingleReqSingleResp not implemented")
}
func (*UnimplementedIGrpcStremServiceServer) SingleReqMultiResp(*SingleRequest, IGrpcStremService_SingleReqMultiRespServer) error {
	return status.Errorf(codes.Unimplemented, "method SingleReqMultiResp not implemented")
}
func (*UnimplementedIGrpcStremServiceServer) MultiReqSingleResp(IGrpcStremService_MultiReqSingleRespServer) error {
	return status.Errorf(codes.Unimplemented, "method MultiReqSingleResp not implemented")
}
func (*UnimplementedIGrpcStremServiceServer) MultiReqMultiResp(IGrpcStremService_MultiReqMultiRespServer) error {
	return status.Errorf(codes.Unimplemented, "method MultiReqMultiResp not implemented")
}

func RegisterIGrpcStremServiceServer(s *grpc.Server, srv IGrpcStremServiceServer) {
	s.RegisterService(&_IGrpcStremService_serviceDesc, srv)
}

func _IGrpcStremService_SingleReqSingleResp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IGrpcStremServiceServer).SingleReqSingleResp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcstream.IGrpcStremService/SingleReqSingleResp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IGrpcStremServiceServer).SingleReqSingleResp(ctx, req.(*SingleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IGrpcStremService_SingleReqMultiResp_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SingleRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IGrpcStremServiceServer).SingleReqMultiResp(m, &iGrpcStremServiceSingleReqMultiRespServer{stream})
}

type IGrpcStremService_SingleReqMultiRespServer interface {
	Send(*SingleResponse) error
	grpc.ServerStream
}

type iGrpcStremServiceSingleReqMultiRespServer struct {
	grpc.ServerStream
}

func (x *iGrpcStremServiceSingleReqMultiRespServer) Send(m *SingleResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _IGrpcStremService_MultiReqSingleResp_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IGrpcStremServiceServer).MultiReqSingleResp(&iGrpcStremServiceMultiReqSingleRespServer{stream})
}

type IGrpcStremService_MultiReqSingleRespServer interface {
	SendAndClose(*SingleResponse) error
	Recv() (*SingleRequest, error)
	grpc.ServerStream
}

type iGrpcStremServiceMultiReqSingleRespServer struct {
	grpc.ServerStream
}

func (x *iGrpcStremServiceMultiReqSingleRespServer) SendAndClose(m *SingleResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *iGrpcStremServiceMultiReqSingleRespServer) Recv() (*SingleRequest, error) {
	m := new(SingleRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _IGrpcStremService_MultiReqMultiResp_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IGrpcStremServiceServer).MultiReqMultiResp(&iGrpcStremServiceMultiReqMultiRespServer{stream})
}

type IGrpcStremService_MultiReqMultiRespServer interface {
	Send(*SingleResponse) error
	Recv() (*SingleRequest, error)
	grpc.ServerStream
}

type iGrpcStremServiceMultiReqMultiRespServer struct {
	grpc.ServerStream
}

func (x *iGrpcStremServiceMultiReqMultiRespServer) Send(m *SingleResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *iGrpcStremServiceMultiReqMultiRespServer) Recv() (*SingleRequest, error) {
	m := new(SingleRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _IGrpcStremService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcstream.IGrpcStremService",
	HandlerType: (*IGrpcStremServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SingleReqSingleResp",
			Handler:    _IGrpcStremService_SingleReqSingleResp_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SingleReqMultiResp",
			Handler:       _IGrpcStremService_SingleReqMultiResp_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "MultiReqSingleResp",
			Handler:       _IGrpcStremService_MultiReqSingleResp_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "MultiReqMultiResp",
			Handler:       _IGrpcStremService_MultiReqMultiResp_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpcstream.proto",
}
