// Code generated by hertz generator.

package main

import (
	handler "webhook/biz/handler"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// 响应alertmanager的webhook
	r.POST("/webhook", handler.AlertmanagerWebhook)
}
